/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantapplication;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import static restaurantapplication.Table1JFrame.table1Orders1;
import static restaurantapplication.Table1JFrame.total;

/**
 *
 * @author canku
 */
public class Tables extends javax.swing.JFrame {

    Table1JFrame table1JFrame = new Table1JFrame();
    Table2JFrame table2JFrame = new Table2JFrame();
    Table3JFrame table3JFrame = new Table3JFrame();
    Table4JFrame table4JFrame = new Table4JFrame();
    Table5JFrame table5JFrame = new Table5JFrame();
    Table6JFrame table6JFrame = new Table6JFrame();
    Table7JFrame table7JFrame = new Table7JFrame();
    Table8JFrame table8JFrame = new Table8JFrame();
    Table9JFrame table9JFrame = new Table9JFrame();
    
    static int totalAmount = 0;    
    /**
     * Creates new form Tables
     */
    public Tables() {
        initComponents();
        
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moneyPanel = new javax.swing.JPanel();
        totalMoneyLabel = new javax.swing.JLabel();
        totalMoneyValue = new javax.swing.JLabel();
        clearTotalMoney = new javax.swing.JButton();
        tablesPanel = new javax.swing.JPanel();
        table1Panel = new javax.swing.JPanel();
        table1Label = new javax.swing.JLabel();
        sitButton1 = new javax.swing.JButton();
        bill1Label = new javax.swing.JLabel();
        bill1Value = new javax.swing.JLabel();
        available1Value = new javax.swing.JLabel();
        table2Panel = new javax.swing.JPanel();
        table2Label = new javax.swing.JLabel();
        sitButton2 = new javax.swing.JButton();
        bill2Label = new javax.swing.JLabel();
        bill2Value = new javax.swing.JLabel();
        available2Value = new javax.swing.JLabel();
        table3Panel = new javax.swing.JPanel();
        table3Label = new javax.swing.JLabel();
        sitButton3 = new javax.swing.JButton();
        bill3Label = new javax.swing.JLabel();
        bill3Value = new javax.swing.JLabel();
        available3Value = new javax.swing.JLabel();
        table4Panel = new javax.swing.JPanel();
        table4Label = new javax.swing.JLabel();
        sitButton4 = new javax.swing.JButton();
        bill4Label = new javax.swing.JLabel();
        bill4Value = new javax.swing.JLabel();
        available4Value = new javax.swing.JLabel();
        table5Panel = new javax.swing.JPanel();
        table5Label = new javax.swing.JLabel();
        sitButton5 = new javax.swing.JButton();
        bill5Label = new javax.swing.JLabel();
        bill5Value = new javax.swing.JLabel();
        available5Value = new javax.swing.JLabel();
        table6Panel = new javax.swing.JPanel();
        table6Label = new javax.swing.JLabel();
        sitButton6 = new javax.swing.JButton();
        bill6Label = new javax.swing.JLabel();
        bill6Value = new javax.swing.JLabel();
        available6Value = new javax.swing.JLabel();
        table7Panel = new javax.swing.JPanel();
        table7Label = new javax.swing.JLabel();
        sitButton7 = new javax.swing.JButton();
        bill7Label = new javax.swing.JLabel();
        bill7Value = new javax.swing.JLabel();
        available7Value = new javax.swing.JLabel();
        table8Panel = new javax.swing.JPanel();
        table8Label = new javax.swing.JLabel();
        sitButton8 = new javax.swing.JButton();
        bill8Label = new javax.swing.JLabel();
        bill8Value = new javax.swing.JLabel();
        available8Value = new javax.swing.JLabel();
        table9Panel = new javax.swing.JPanel();
        table9Label = new javax.swing.JLabel();
        sitButton9 = new javax.swing.JButton();
        bill9Label = new javax.swing.JLabel();
        bill9Value = new javax.swing.JLabel();
        available9Value = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        moneyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        totalMoneyLabel.setText("Total Money Earned : ");

        totalMoneyValue.setText("0");

        clearTotalMoney.setText("Clear Total Money");
        clearTotalMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTotalMoneyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout moneyPanelLayout = new javax.swing.GroupLayout(moneyPanel);
        moneyPanel.setLayout(moneyPanelLayout);
        moneyPanelLayout.setHorizontalGroup(
            moneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moneyPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(totalMoneyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalMoneyValue, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearTotalMoney)
                .addContainerGap())
        );
        moneyPanelLayout.setVerticalGroup(
            moneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moneyPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(moneyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalMoneyLabel)
                    .addComponent(totalMoneyValue)
                    .addComponent(clearTotalMoney))
                .addGap(18, 18, 18))
        );

        tablesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        table1Panel.setBackground(java.awt.Color.green);
        table1Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table1Panel.setPreferredSize(new java.awt.Dimension(135, 135));

        table1Label.setText("Table 1");

        sitButton1.setText("Sit");
        sitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitButton1ActionPerformed(evt);
            }
        });

        bill1Label.setText("Bill :");

        bill1Value.setText("0");

        available1Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        available1Value.setText("Available");

        javax.swing.GroupLayout table1PanelLayout = new javax.swing.GroupLayout(table1Panel);
        table1Panel.setLayout(table1PanelLayout);
        table1PanelLayout.setHorizontalGroup(
            table1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table1PanelLayout.createSequentialGroup()
                .addGroup(table1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(table1PanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(table1Label))
                    .addGroup(table1PanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(table1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(table1PanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bill1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bill1Value)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(available1Value, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        table1PanelLayout.setVerticalGroup(
            table1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table1Label)
                .addGap(18, 18, 18)
                .addComponent(sitButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(table1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill1Label)
                    .addComponent(bill1Value))
                .addGap(13, 13, 13)
                .addComponent(available1Value)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        table2Panel.setBackground(java.awt.Color.green);
        table2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table2Panel.setPreferredSize(new java.awt.Dimension(135, 135));

        table2Label.setText("Table 2");

        sitButton2.setText("Sit");
        sitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitButton2ActionPerformed(evt);
            }
        });

        bill2Label.setText("Bill :");

        bill2Value.setText("0");

        available2Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        available2Value.setText("Available");

        javax.swing.GroupLayout table2PanelLayout = new javax.swing.GroupLayout(table2Panel);
        table2Panel.setLayout(table2PanelLayout);
        table2PanelLayout.setHorizontalGroup(
            table2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table2PanelLayout.createSequentialGroup()
                .addGroup(table2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(table2PanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(table2Label))
                    .addGroup(table2PanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(table2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(table2PanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bill2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bill2Value)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(available2Value, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        table2PanelLayout.setVerticalGroup(
            table2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table2Label)
                .addGap(18, 18, 18)
                .addComponent(sitButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(table2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill2Label)
                    .addComponent(bill2Value))
                .addGap(13, 13, 13)
                .addComponent(available2Value)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        table3Panel.setBackground(java.awt.Color.green);
        table3Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table3Panel.setPreferredSize(new java.awt.Dimension(135, 135));

        table3Label.setText("Table 3");

        sitButton3.setText("Sit");
        sitButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitButton3ActionPerformed(evt);
            }
        });

        bill3Label.setText("Bill :");

        bill3Value.setText("0");

        available3Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        available3Value.setText("Available");

        javax.swing.GroupLayout table3PanelLayout = new javax.swing.GroupLayout(table3Panel);
        table3Panel.setLayout(table3PanelLayout);
        table3PanelLayout.setHorizontalGroup(
            table3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table3PanelLayout.createSequentialGroup()
                .addGroup(table3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(table3PanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(table3Label))
                    .addGroup(table3PanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(table3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sitButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(table3PanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bill3Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bill3Value)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(available3Value, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        table3PanelLayout.setVerticalGroup(
            table3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table3Label)
                .addGap(18, 18, 18)
                .addComponent(sitButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(table3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill3Label)
                    .addComponent(bill3Value))
                .addGap(13, 13, 13)
                .addComponent(available3Value)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        table4Panel.setBackground(java.awt.Color.green);
        table4Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table4Panel.setPreferredSize(new java.awt.Dimension(135, 135));

        table4Label.setText("Table 4");

        sitButton4.setText("Sit");
        sitButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitButton4ActionPerformed(evt);
            }
        });

        bill4Label.setText("Bill :");

        bill4Value.setText("0");

        available4Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        available4Value.setText("Available");

        javax.swing.GroupLayout table4PanelLayout = new javax.swing.GroupLayout(table4Panel);
        table4Panel.setLayout(table4PanelLayout);
        table4PanelLayout.setHorizontalGroup(
            table4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table4PanelLayout.createSequentialGroup()
                .addGroup(table4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(table4PanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(table4Label))
                    .addGroup(table4PanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(table4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sitButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(table4PanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bill4Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bill4Value)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(available4Value, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        table4PanelLayout.setVerticalGroup(
            table4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table4Label)
                .addGap(18, 18, 18)
                .addComponent(sitButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(table4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill4Label)
                    .addComponent(bill4Value))
                .addGap(13, 13, 13)
                .addComponent(available4Value)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        table5Panel.setBackground(java.awt.Color.green);
        table5Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table5Panel.setPreferredSize(new java.awt.Dimension(135, 135));

        table5Label.setText("Table 5");

        sitButton5.setText("Sit");
        sitButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitButton5ActionPerformed(evt);
            }
        });

        bill5Label.setText("Bill :");

        bill5Value.setText("0");

        available5Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        available5Value.setText("Available");

        javax.swing.GroupLayout table5PanelLayout = new javax.swing.GroupLayout(table5Panel);
        table5Panel.setLayout(table5PanelLayout);
        table5PanelLayout.setHorizontalGroup(
            table5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table5PanelLayout.createSequentialGroup()
                .addGroup(table5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(table5PanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(table5Label))
                    .addGroup(table5PanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(table5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sitButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(table5PanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bill5Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bill5Value)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(available5Value, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        table5PanelLayout.setVerticalGroup(
            table5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table5PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table5Label)
                .addGap(18, 18, 18)
                .addComponent(sitButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(table5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill5Label)
                    .addComponent(bill5Value))
                .addGap(13, 13, 13)
                .addComponent(available5Value)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        table6Panel.setBackground(java.awt.Color.green);
        table6Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table6Panel.setPreferredSize(new java.awt.Dimension(135, 135));

        table6Label.setText("Table 6");

        sitButton6.setText("Sit");
        sitButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitButton6ActionPerformed(evt);
            }
        });

        bill6Label.setText("Bill :");

        bill6Value.setText("0");

        available6Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        available6Value.setText("Available");

        javax.swing.GroupLayout table6PanelLayout = new javax.swing.GroupLayout(table6Panel);
        table6Panel.setLayout(table6PanelLayout);
        table6PanelLayout.setHorizontalGroup(
            table6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table6PanelLayout.createSequentialGroup()
                .addGroup(table6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(table6PanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(table6Label))
                    .addGroup(table6PanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(table6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sitButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(table6PanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bill6Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bill6Value)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(available6Value, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        table6PanelLayout.setVerticalGroup(
            table6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table6PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table6Label)
                .addGap(18, 18, 18)
                .addComponent(sitButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(table6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill6Label)
                    .addComponent(bill6Value))
                .addGap(13, 13, 13)
                .addComponent(available6Value)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        table7Panel.setBackground(java.awt.Color.green);
        table7Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table7Panel.setPreferredSize(new java.awt.Dimension(135, 135));

        table7Label.setText("Table 7");

        sitButton7.setText("Sit");
        sitButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitButton7ActionPerformed(evt);
            }
        });

        bill7Label.setText("Bill :");

        bill7Value.setText("0");

        available7Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        available7Value.setText("Available");

        javax.swing.GroupLayout table7PanelLayout = new javax.swing.GroupLayout(table7Panel);
        table7Panel.setLayout(table7PanelLayout);
        table7PanelLayout.setHorizontalGroup(
            table7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table7PanelLayout.createSequentialGroup()
                .addGroup(table7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(table7PanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(table7Label))
                    .addGroup(table7PanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(table7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sitButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(table7PanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bill7Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bill7Value)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(available7Value, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        table7PanelLayout.setVerticalGroup(
            table7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table7PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table7Label)
                .addGap(18, 18, 18)
                .addComponent(sitButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(table7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill7Label)
                    .addComponent(bill7Value))
                .addGap(13, 13, 13)
                .addComponent(available7Value)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        table8Panel.setBackground(java.awt.Color.green);
        table8Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table8Panel.setPreferredSize(new java.awt.Dimension(135, 135));

        table8Label.setText("Table 8");

        sitButton8.setText("Sit");
        sitButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitButton8ActionPerformed(evt);
            }
        });

        bill8Label.setText("Bill :");

        bill8Value.setText("0");

        available8Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        available8Value.setText("Available");

        javax.swing.GroupLayout table8PanelLayout = new javax.swing.GroupLayout(table8Panel);
        table8Panel.setLayout(table8PanelLayout);
        table8PanelLayout.setHorizontalGroup(
            table8PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table8PanelLayout.createSequentialGroup()
                .addGroup(table8PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(table8PanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(table8Label))
                    .addGroup(table8PanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(table8PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sitButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(table8PanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bill8Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bill8Value)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(available8Value, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        table8PanelLayout.setVerticalGroup(
            table8PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table8PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table8Label)
                .addGap(18, 18, 18)
                .addComponent(sitButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(table8PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill8Label)
                    .addComponent(bill8Value))
                .addGap(13, 13, 13)
                .addComponent(available8Value)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        table9Panel.setBackground(java.awt.Color.green);
        table9Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table9Panel.setPreferredSize(new java.awt.Dimension(135, 135));

        table9Label.setText("Table 9");

        sitButton9.setText("Sit");
        sitButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sitButton9ActionPerformed(evt);
            }
        });

        bill9Label.setText("Bill :");

        bill9Value.setText("0");

        available9Value.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        available9Value.setText("Available");

        javax.swing.GroupLayout table9PanelLayout = new javax.swing.GroupLayout(table9Panel);
        table9Panel.setLayout(table9PanelLayout);
        table9PanelLayout.setHorizontalGroup(
            table9PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table9PanelLayout.createSequentialGroup()
                .addGroup(table9PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(table9PanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(table9Label))
                    .addGroup(table9PanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(table9PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sitButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(table9PanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bill9Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bill9Value)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(available9Value, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        table9PanelLayout.setVerticalGroup(
            table9PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(table9PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(table9Label)
                .addGap(18, 18, 18)
                .addComponent(sitButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(table9PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill9Label)
                    .addComponent(bill9Value))
                .addGap(13, 13, 13)
                .addComponent(available9Value)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tablesPanelLayout = new javax.swing.GroupLayout(tablesPanel);
        tablesPanel.setLayout(tablesPanelLayout);
        tablesPanelLayout.setHorizontalGroup(
            tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablesPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table7Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(table8Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table3Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table6Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table9Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
        tablesPanelLayout.setVerticalGroup(
            tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablesPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table6Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(tablesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(table8Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table9Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(table7Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tablesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(moneyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moneyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tablesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  
    public static void changeLabel (){
        totalMoneyValue.setText(Integer.toString(totalAmount));
    }
            
    private void sitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitButton1ActionPerformed
        
        this.toBack();
        table1JFrame.setVisible(true);
        table1JFrame.toFront();
        Menu.selection =1;
       
        // TODO add your handling code here:
    }//GEN-LAST:event_sitButton1ActionPerformed

    private void sitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitButton2ActionPerformed

        this.toBack();
        table2JFrame.setVisible(true);
        table2JFrame.toFront();
        Menu.selection =2;
        
        // TODO add your handling code here:
    }//GEN-LAST:event_sitButton2ActionPerformed

    private void sitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitButton3ActionPerformed
        
        this.toBack();
        table3JFrame.setVisible(true);
        table3JFrame.toFront();
        Menu.selection =3;
        
        // TODO add your handling code here:
    }//GEN-LAST:event_sitButton3ActionPerformed

    private void sitButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitButton4ActionPerformed
        
        this.toBack();
        table4JFrame.setVisible(true);
        table4JFrame.toFront();
        Menu.selection =4;
        
        // TODO add your handling code here:
    }//GEN-LAST:event_sitButton4ActionPerformed

    private void sitButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitButton5ActionPerformed
 
        this.toBack();
        table5JFrame.setVisible(true);
        table5JFrame.toFront();
        Menu.selection =5;

        // TODO add your handling code here:
    }//GEN-LAST:event_sitButton5ActionPerformed

    private void sitButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitButton6ActionPerformed
 
        this.toBack();
        table6JFrame.setVisible(true);
        table6JFrame.toFront();
        Menu.selection =6;

        // TODO add your handling code here:
    }//GEN-LAST:event_sitButton6ActionPerformed

    private void sitButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitButton7ActionPerformed
 
        this.toBack();
        table7JFrame.setVisible(true);
        table7JFrame.toFront();
        Menu.selection =7;
        
        // TODO add your handling code here:
    }//GEN-LAST:event_sitButton7ActionPerformed

    private void sitButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitButton8ActionPerformed
 
        this.toBack();
        table8JFrame.setVisible(true);
        table8JFrame.toFront();
        Menu.selection =8;
        
        // TODO add your handling code here:
    }//GEN-LAST:event_sitButton8ActionPerformed

    private void sitButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sitButton9ActionPerformed
  
        this.toBack();
        table9JFrame.setVisible(true);
        table9JFrame.toFront();
        Menu.selection =9;
        
        // TODO add your handling code here:
    }//GEN-LAST:event_sitButton9ActionPerformed

    private void clearTotalMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTotalMoneyActionPerformed

        totalAmount = 0;
        totalMoneyValue.setText("0");
        // TODO add your handling code here:
    }//GEN-LAST:event_clearTotalMoneyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel available1Value;
    public static javax.swing.JLabel available2Value;
    public static javax.swing.JLabel available3Value;
    public static javax.swing.JLabel available4Value;
    public static javax.swing.JLabel available5Value;
    public static javax.swing.JLabel available6Value;
    public static javax.swing.JLabel available7Value;
    public static javax.swing.JLabel available8Value;
    public static javax.swing.JLabel available9Value;
    private javax.swing.JLabel bill1Label;
    public static javax.swing.JLabel bill1Value;
    private javax.swing.JLabel bill2Label;
    public static javax.swing.JLabel bill2Value;
    private javax.swing.JLabel bill3Label;
    public static javax.swing.JLabel bill3Value;
    private javax.swing.JLabel bill4Label;
    public static javax.swing.JLabel bill4Value;
    private javax.swing.JLabel bill5Label;
    public static javax.swing.JLabel bill5Value;
    private javax.swing.JLabel bill6Label;
    public static javax.swing.JLabel bill6Value;
    private javax.swing.JLabel bill7Label;
    public static javax.swing.JLabel bill7Value;
    private javax.swing.JLabel bill8Label;
    public static javax.swing.JLabel bill8Value;
    private javax.swing.JLabel bill9Label;
    public static javax.swing.JLabel bill9Value;
    private javax.swing.JButton clearTotalMoney;
    private javax.swing.JPanel moneyPanel;
    private javax.swing.JButton sitButton1;
    private javax.swing.JButton sitButton2;
    private javax.swing.JButton sitButton3;
    private javax.swing.JButton sitButton4;
    private javax.swing.JButton sitButton5;
    private javax.swing.JButton sitButton6;
    private javax.swing.JButton sitButton7;
    private javax.swing.JButton sitButton8;
    private javax.swing.JButton sitButton9;
    private javax.swing.JLabel table1Label;
    public static javax.swing.JPanel table1Panel;
    private javax.swing.JLabel table2Label;
    public static javax.swing.JPanel table2Panel;
    private javax.swing.JLabel table3Label;
    public static javax.swing.JPanel table3Panel;
    private javax.swing.JLabel table4Label;
    public static javax.swing.JPanel table4Panel;
    private javax.swing.JLabel table5Label;
    public static javax.swing.JPanel table5Panel;
    private javax.swing.JLabel table6Label;
    public static javax.swing.JPanel table6Panel;
    private javax.swing.JLabel table7Label;
    public static javax.swing.JPanel table7Panel;
    private javax.swing.JLabel table8Label;
    public static javax.swing.JPanel table8Panel;
    private javax.swing.JLabel table9Label;
    public static javax.swing.JPanel table9Panel;
    private javax.swing.JPanel tablesPanel;
    private javax.swing.JLabel totalMoneyLabel;
    public static javax.swing.JLabel totalMoneyValue;
    // End of variables declaration//GEN-END:variables
}
